services:
  postgres:
    image: 'postgres:16'
    restart: always
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_backups:/pgadmin/backups
    networks:
      - backend

  adminer: # Легче, чем pgAdmin!
    image: adminer
    restart: always
    ports:
      - 8088:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nette # Красивая тема
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
